[build]
command = 'hugo'
publish = 'public'
baseURL = "https://xingyu-chen.netlify.app/"

[build.environment]
HUGO_VERSION = '0.134.0'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
